name=RoboWallet
version=0.1.0
author=SolM2M Labs
maintainer=SolM2M Labs <developer@solm2m.com>
sentence=Solana M2M embedded SDK wrapper for Arduino.
paragraph=A lightweight wrapper exposing the Rust `no_std` RoboWallet Core functionality to Arduino IDE projects on ESP32 microcontrollers.
category=Communication
url=https://github.com/SolM2M-Labs/robowallet-core
architectures=esp32,esp32s2,esp32c3
